<a href="https://colab.research.google.com/github/NyokoKei/Learning/blob/main/assignment_1_all_about_torch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1 - All About torch.Tensor

<a target="_blank" href="https://colab.research.google.com/github/JovianHQ/notebooks/blob/main/deep-learning-with-pytorch-zero-to-gans/assignment-1-all-about-torch-tensor/assignment-1-all-about-torch-tensor.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>


### 5 interesting functions related to PyTorch tensors

PyTorch is a library used for effective coding for ML, DL, NLP, etc.. The following functions I suppose would be commonly used during data preprocessing for further training.
- function 1: `torhc.squeeze()` https://docs.pytorch.org/docs/2.14/generated/torch.squeeze.html
- function 2 `torch.unsqueeze()` https://docs.pytorch.org/docs/2.14/generated/torch.unsqueeze.html
- function 3 `torch.rand()` https://docs.pytorch.org/docs/2.14/generated/torch.rand.html#torch.rand
- function 4 `torch.cat()` https://docs.pytorch.org/docs/2.14/generated/torch.cat.html
- function 5 `torch.hsplit()` https://docs.pytorch.org/docs/2.14/generated/torch.hsplit.html

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.squeeze

Returns a tensor with all specified dimensions of input of size 1 removed.

In [ ]:
x = torch.zeros(5, 3, 1, 3, 2, 1)
print(x.shape)
print(x.squeeze().shape)

torch.Size([5, 3, 1, 3, 2, 1])
torch.Size([5, 3, 3, 2])


Removes all brackets of size 1

In [ ]:
# Example 2 - working
x = torch.zeros(5, 3, 1, 3, 2, 1)
print(x.shape)
print(x.squeeze([2, 3]).shape)

torch.Size([5, 3, 1, 3, 2, 1])
torch.Size([5, 3, 3, 2, 1])


Removes specified index of dimensions if their size is 1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.zeros(5, 3, 1, 3, 2, 2)
print(x.shape)
print(x.squeeze(dim=7).shape)

torch.Size([5, 3, 1, 3, 2, 2])


IndexError: Dimension out of range (expected to be in range of [-6, 5], but got 7)

Dimension to remove is out of range

Use the function when need to reduce the matrix sizes by removing unnecessary brackets

## Function 2 - torch.unsqueeze()

Add dimension of size 1 to the specific position

In [ ]:
x2 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x2)
print(x2.size())
print("="*30)

x2 = x2.unsqueeze(1)
print(x2)
print(x2.size())
print("="*30)

x2 = x2.squeeze().unsqueeze(2)
print(x2)
print(x2.size())

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])
torch.Size([2, 1, 4])
tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]])
torch.Size([2, 4, 1])


Inserts brackets to a specific index in the tensor

In [ ]:
# Example 2 - working
x2 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x2)
print(x2.size())
print("="*30)

x2 = x2.unsqueeze(-1)
print(x2)
print(x2.size())
print("="*30)

x2 = x2.squeeze().unsqueeze(-3)
print(x2)
print(x2.size())

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]])
torch.Size([2, 4, 1])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
torch.Size([1, 2, 4])


indexing the unsuqeeze value works the same way as with array indexing

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x2 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x2)
print(x2.size())
print("="*30)

x2 = x2.unsqueeze(dim=[2, 3])
print(x2)
print(x2.size())
print("="*30)


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])


TypeError: unsqueeze(): argument 'dim' must be int, not list

Unlike `torch.squeeze()` dim parameter takes only int values

Usefule for operation with tensors which require specific dimension's size

## Function 3 - torch.rand()

Returns a tensor filled with random numbers from a uniform distribution on the interval `[0, 1)`

In [ ]:
# Example 1 - working
print(torch.rand(3))

tensor([0.5104, 0.0144, 0.8996])


Creates a vector of size 3 with random values

In [ ]:
# Example 2 - working
x3 = torch.rand(2, 3, 4)
print(x3)
x3.size()

tensor([[[0.9029, 0.1310, 0.2213, 0.0534],
         [0.2355, 0.3435, 0.1108, 0.7583],
         [0.2104, 0.2164, 0.8130, 0.1853]],

        [[0.5387, 0.4159, 0.3924, 0.5057],
         [0.5798, 0.7596, 0.8643, 0.4033],
         [0.0503, 0.8701, 0.0564, 0.1157]]])


torch.Size([2, 3, 4])

Creates a matrix of the size (2, 3, 4)

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x3 = torch.rand(-1)
x3

RuntimeError: Trying to create tensor with negative dimension -1: [-1]

The size of the desired tensor should be positive

Usefule for fast checking and creating initial values for further algorithm

## Function 4 - torch.cat()

Concatenates the given sequence of tensors in tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be a 1-D empty tensor with size (0,).

In [ ]:
# Example 1 - working
x4 = torch.randint(10, (2, 3))
y4 = torch.randint(10, (1, 3))
z4 = torch.cat((x4, y4), 0)
print(z4)
print(z4.size())

tensor([[3, 5, 0],
        [5, 6, 7],
        [5, 7, 8]])
torch.Size([3, 3])


Concatenates rows

In [ ]:
# Example 2 - working
x4 = torch.randint(10, (2, 3))
y4 = torch.randint(10, (2, 5))
z4 = torch.cat((x4, y4), 1)
print(z4)
print(z4.size())

tensor([[7, 9, 5, 6, 0, 7, 8, 2],
        [8, 6, 1, 1, 9, 1, 9, 0]])
torch.Size([2, 8])


Concatenates by columns

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
x4 = torch.randint(10, (2, 3, 3))
y4 = torch.randint(10, (2, 3, 4))
z4 = torch.cat((x4, y4), 1)
print(z4)
print(z4.size())

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 3 but got size 4 for tensor number 1 in the list.

To be concatenated tensors should have the same dimension except for one by which the operation is conducted

To combine data points for the specific task (e.g. preprocessing)

## Function 5 - torch.hsplit()

Splits vector/matrix horizontally (same rows diff columns)

In [ ]:
# Example 1 - working
x5 = torch.arange(20, dtype=torch.int64).reshape(2, 10)
print(x5)
print("="*50)

x6, x7 = torch.hsplit(x5, 2)
print(x6, x7, sep='\n')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]])
tensor([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])


Splits into 2 equal tensors horizontally

In [ ]:
# Example 2 - working
x5 = torch.arange(20, dtype=torch.int64).reshape(2, 10)
print(x5)
print("="*50)

x51, x52, x53 = torch.hsplit(x5, [3, 10])
print(x51, x52, x53, sep='\n')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2],
        [10, 11, 12]])
tensor([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19]])
tensor([], size=(2, 0), dtype=torch.int64)


[3, 10] Means that splitting points are columns' indexes [0, 2], [3, 9], []

Since max idx is 9, then second tensor is [3, 9] and the next one is blank

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 2 - working
x5 = torch.arange(20, dtype=torch.int64).reshape(2, 10)
print(x5)
print("="*50)

x5 = torch.hsplit(x5, 6)
print(x5, sep='\n')

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])


RuntimeError: torch.hsplit attempted to split along dimension 1, but the size of the dimension 10 is not divisible by the split_size 6!

If indices_or_sections is int and its value cannot be divided by the column size, there will be an error

To split features and target etc

## Conclusion

I covered some torch functions, which may be useful and commonly used during further training in DL, NLP, etc. Also got familiar with the usage of torch documentation.